version: '2.1'
executors:
  gradle:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
  go:
    docker:
      - image: circleci/golang:1.15

commands:
  retrieve_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
  create_or_update_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

jobs:
  test:
    executor: gradle
    steps:
      - checkout
      - retrieve_cache
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Run pluginVerifier
          command: ./gradlew runPluginVerifier
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test
          when: always
      - create_or_update_cache

  build:
    executor: gradle
    steps:
      - checkout
      - retrieve_cache
      - run:
          name: Build plugin
          command: ./gradlew buildPlugin
      - store_artifacts:
          path: build/distributions
      - persist_to_workspace:
          name: Persist plugin file
          root: .
          paths:
            - build/distributions
      - create_or_update_cache

  publish_to_marketplace:
    executor: gradle
    steps:
      - checkout
      - retrieve_cache
      - attach_workspace:
          at: .
          name: Retrieve plugin file
      - run:
          name: Publish plugin
          command: ./gradlew publishPlugin

  github_release:
    executor: go
    steps:
      - checkout
      - attach_workspace:
          at: .
          name: Retrieve plugin file
      - github-release/setup
      - github-release/create-release
      - github-release/upload-files:
          file_pattern: 'build/distributions/*'
workflows:
  continious:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
          requires:
            - test
      - github_release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish_to_marketplace:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
